travis:
  secure:
    BINSTAR_TOKEN: OQTGqem4+Cm4/0bgVhkpNqQ+TNBdVrMXzkzy1J18SXbcbQKVqkugkqDOKRDVAB7ABbkc8JNr+1EfYg8JJ87MNmvtQhWWslSLvX28/syp9VwEPrANtRbkfgkRjA5Pyqu0kamRkCpDQBAxTv6ESdKLAb1A9aIOzd60smnnXu5aYq2r0ozETKnCK7ZqCBkpZ8+idbUOsp88vHuLHltA/+O80U0lcKPKlo53ACNnivMFzgAKRfdIX2e2gHWd48x3OBZM+4ZV9FUDyZPZoHDXEfP5h0WgO5f5YcrNSXJj5rqGwU18CST72nzU30SkrrffnUMjigqdT2gwR4vOhJT6/2QUhNfVFArnJeQY83DLOanjTpZl/TI8/6vnmeZXsP/FqcHbaAMh3AmUdTjl+pFbCWBsX0h/42fVCIaSRVylAj83Vno/bdCaj+tCN1l1VWYQg8FE13QyiIUBMtuPb7+hybj45v/jzx+b8x0x1JaHV35udNX4NeAN5h8be2wnVO1zyCYiZ2aHaqCC/unfefunL4MJ1b8ZV6/6XPC8Mlpn2dHjzTHT3SmSrJikPBkP3bnXe2JE4R+zHfSbBXSH/nYSIkKaWpCqge64b3PAlBdrxFgdZz4j7wO+hgO0OcWjO1twkGWxdsAO0XyOyNQs8rsBXoZ448ybQ6UH/vycfyH9pK7//7M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
