travis:
  secure:
    BINSTAR_TOKEN: ACv2rCr1wrho5IUvCUWlYd/8yOJ+g3CIlYCTb6ylhqpl6wHP6wsWiTjo0pNeq5m7d8FwHwGx8TkK2rWFYzSwdaGvFRiFONV6/QRFnFi0rEbqReVBJ5AfxM55LbSrx4RsVp+lkN5USxAsUZSiLzV3R784TFXf+mvIwSLTYAH9KZt2FHEyVxr0CHDHKcbxs/2EvjQvKLmdDyneOZv3xxa745qwyvHu6qRuOgf+oFyNo1D5grQzCHvr6T/hWe2VVRlXYofTPZ32DaqYrZ/BqOdUSoRWBgmDNi1vyZyV/MFhriBLGSfaYD6W5N8rVjQ5w30BtlKZhNcugb/bPbpbV3NAIKpRalC4mqR9CqUld8ZHj1pARtnEijeA4SF+9xYU0LZXMqjUU38ROhotcnY8yWNpKj2m3QrASPxc0mFIPD2URUSnZbaZs9Tpb7qYipC2rw0NvTezIz3lTgQnE6VGM2ivk3ytygMXQKBaRehHFxE/Vgxs8w3969YihfP0QYCj3oVhCgZ6phrdzubNdRV9ZAQUJfxrFXeJL95gvXak63OGz2gFmJjEPDQOPtukJta0fxizvjVHkn0PpbcParYAZcI5iktxBPnB41nmh+q2AKvvfG81DHyNY1L5Yqcfc3EzmsG2gKqeTbJt2UV+gRsFMbWLCvpTfgR9qnyuAZouW3SjEyQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
